In [1]:
import re
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfTransformer
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from keras.preprocessing.text import one_hot
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.embeddings import Embedding

In [2]:
emotion_final = pd.read_csv("/home/apprenant/simplon_project/Brief-Emotion-Analysis-Text/data/02_cleaned/cleaned_emotion_final.csv")

In [3]:
text_emotion = pd.read_csv("/home/apprenant/simplon_project/Brief-Emotion-Analysis-Text/data/02_cleaned/cleaned_text_emotion.csv")

In [4]:
conditions = [(emotion_final['label'] == "sadness") | (emotion_final['label'] == "anger"),  (emotion_final['label'] == "surprise") | (emotion_final['label'] == "fear") ,(emotion_final['label'] == "love") | (emotion_final['label'] == "happy")] 
values = [0, 1, 2]

In [5]:
emotion_final['binary_emotion'] = np.select(conditions, values)

In [6]:
emotion_final.head(15)

text     label  \
0                             i didnt feel humiliated   sadness   
1   i can go from feeling so hopeless to so damned...   sadness   
2    im grabbing a minute to post i feel greedy wrong     anger   
3   i am ever feeling nostalgic about the fireplac...      love   
4                                i am feeling grouchy     anger   
5   ive been feeling a little burdened lately wasn...   sadness   
6   ive been taking or milligrams or times recomme...  surprise   
7   i feel as confused about life as a teenager or...      fear   
8   i have been with petronas for years i feel tha...     happy   
9                                 i feel romantic too      love   
10  i feel like i have to make the suffering i m s...   sadness   
11  i do feel that running is a divine experience ...     happy   
12  i think it s the easiest time of year to feel ...     anger   
13                 i feel low energy i m just thirsty   sadness   
14  i have immense sympathy with the general point...     happy   

    binary_emotion  
0                0  
1                0  
2                0  
3                2  
4                0  
5                0  
6                1  
7                1  
8                2  
9                2  
10               0  
11               2  
12               0  
13               0  
14               2

In [7]:
X = emotion_final['text']
y = emotion_final['binary_emotion']
X_test = emotion_final['text']
y_test = emotion_final['binary_emotion']


In [8]:
type(X)

pandas.core.series.Series

In [9]:
X = X.to_list()
y = y.to_numpy()
X_test = X_test.to_list()
y_test = y_test.to_numpy()

In [10]:
#for value in X : 
#    #value = str(value)
#    value = re.sub(r'\d+', '',value)

In [11]:
liste = []
for value in X : 
    value = value.split()
    number_of_word = len(value)
    liste.append(number_of_word)
liste.sort()
print(liste)

26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 

In [12]:

vs = 10000
enc_docs = [one_hot(d , vs) for d in X]
enc_docs_test = [one_hot(d , vs) for d in X_test]

In [13]:
max_length = 66
p_docs = pad_sequences(enc_docs, maxlen = max_length, padding = 'post')
p_docs_test = pad_sequences(enc_docs_test, maxlen = max_length, padding = 'post')
print(p_docs)


[[4356 7128 9285 ...    0    0    0]
 [4356 1407 9160 ...    0    0    0]
 [ 797  684 6370 ...    0    0    0]
 ...
 [8657 5975 8254 ...    0    0    0]
 [4052 5258 8978 ...    0    0    0]
 [4356  609 6353 ...    0    0    0]]


In [14]:
print(p_docs_test)

[[4356 7128 9285 ...    0    0    0]
 [4356 1407 9160 ...    0    0    0]
 [ 797  684 6370 ...    0    0    0]
 ...
 [8657 5975 8254 ...    0    0    0]
 [4052 5258 8978 ...    0    0    0]
 [4356  609 6353 ...    0    0    0]]


In [15]:
y = keras.utils.to_categorical(y, 3)
y_test = keras.utils.to_categorical(y_test, 3)

In [16]:
early_stopping = keras.callbacks.EarlyStopping(
    patience=20,
    min_delta=0.001,
    restore_best_weights=True,
)

In [18]:
# define the model
modelEmb = Sequential()
modelEmb.add(Embedding(vs, 500, input_length=max_length))
modelEmb.add(Flatten())
modelEmb.add(Dense(64, activation='relu'))
modelEmb.add(Dense(64, activation='relu'))
modelEmb.add(Dense(64, activation='relu'))
modelEmb.add(Dense(3, activation='softmax'))
# compile the model
modelEmb.compile(optimizer='adam',loss = keras.losses.categorical_crossentropy, metrics=['accuracy'])
# summarize the model
print(modelEmb.summary())
# fit the model
modelEmb.fit(p_docs, y, epochs = 20, callbacks = [early_stopping], verbose=1, validation_data = (p_docs_test, y_test))

score = modelEmb.evaluate(p_docs_test, y_test, verbose=1)

print('Test loss:', score[0])
print('Test accuracy:', score[1])
# evaluate the model
#history_df = pd.DataFrame(history.history)
## Start the plot at epoch 5
#history_df.loc[5:, ['loss', 'val_loss']].plot()
#history_df.loc[5:, ['accuracy', 'val_accuracy']].plot()
#
#print(("Best Validation Loss: {:0.4f}" +\
#      "\nBest Validation Accuracy: {:0.4f}")\
#      .format(history_df['val_loss'].min(), 
#              history_df['val_accuracy'].max()))
#loss, accuracy = modelEmb.evaluate(p_docs, y, verbose=2)
#print('Accuracy: %f' % (accuracy*100))

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 66, 500)           5000000   
_________________________________________________________________
flatten_1 (Flatten)          (None, 33000)             0         
_________________________________________________________________
dense_4 (Dense)              (None, 64)                2112064   
_________________________________________________________________
dense_5 (Dense)              (None, 64)                4160      
_________________________________________________________________
dense_6 (Dense)              (None, 64)                4160      
_________________________________________________________________
dense_7 (Dense)              (None, 3)                 195       
Total params: 7,120,579
Trainable params: 7,120,579
Non-trainable params: 0
____________________________________________

In [21]:
conditions = [ (text_emotion['label'] == "sadness") | (text_emotion['label'] == "worry") | (text_emotion['label'] == "hate")  | (text_emotion['label'] == "anger"), (text_emotion['label'] == "boredom") | (text_emotion['label'] == "surprise") |(text_emotion['label'] == "empty") | (text_emotion['label'] == "neutral"), (text_emotion['label'] == "love") | (text_emotion['label'] == "fun") | (text_emotion['label'] == "happiness") | (text_emotion['label'] == "relief") | (text_emotion['label'] == "enthusiasm")] 
values = [0, 1, 2]

In [22]:
text_emotion['binary_emotion'] = np.select(conditions, values)

In [24]:
text_emotion.head(15)

tweet_id       label                                               text  \
0   1956967341       empty  @tiffanylue i know  i was listenin to bad habi...   
1   1956967666     sadness  Layin n bed with a headache  ughhhh...waitin o...   
2   1956967696     sadness                Funeral ceremony...gloomy friday...   
3   1956967789  enthusiasm               wants to hang out with friends SOON!   
4   1956968416     neutral  @dannycastillo We want to trade with someone w...   
5   1956968477       worry  Re-pinging @ghostridah14: why didn't you go to...   
6   1956968487     sadness  I should be sleep, but im not! thinking about ...   
7   1956968636       worry               Hmmm. http://www.djhero.com/ is down   
8   1956969035     sadness            @charviray Charlene my love. I miss you   
9   1956969172     sadness         @kelcouch I'm sorry  at least it's Friday?   
10  1956969456     neutral                                   cant fall asleep   
11  1956969531       worry                            Choked on her retainers   
12  1956970047     sadness  Ugh! I have to beat this stupid song to get to...   
13  1956970424     sadness  @BrodyJenner if u watch the hills in london u ...   
14  1956970860    surprise                                       Got the news   

    binary_emotion  
0                1  
1                0  
2                0  
3                2  
4                1  
5                0  
6                0  
7                0  
8                0  
9                0  
10               1  
11               0  
12               0  
13               0  
14               1

In [25]:
X = text_emotion['text']
y = text_emotion['binary_emotion']
X_test = text_emotion['text']
y_test = text_emotion['binary_emotion']

In [26]:
X = X.to_list()
y = y.to_numpy()
X_test = X_test.to_list()
y_test = y_test.to_numpy()

In [27]:
liste = []
for value in X : 
    value = value.split()
    number_of_word = len(value)
    liste.append(number_of_word)
liste.sort()
print(liste)

23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 

In [28]:
vs = 10000
enc_docs = [one_hot(d , vs) for d in X]
enc_docs_test = [one_hot(d , vs) for d in X_test]

In [29]:
max_length = 34
p_docs = pad_sequences(enc_docs, maxlen = max_length, padding = 'post')
p_docs_test = pad_sequences(enc_docs_test, maxlen = max_length, padding = 'post')
print(p_docs)

[[ 789 4356 7578 ...    0    0    0]
 [1967 1450 4705 ...    0    0    0]
 [7641 4581 3018 ...    0    0    0]
 ...
 [6469 7513 9528 ...    0    0    0]
 [9249 3244 1021 ...    0    0    0]
 [6634 5957 5830 ...    0    0    0]]


In [30]:
print(p_docs_test)

[[ 789 4356 7578 ...    0    0    0]
 [1967 1450 4705 ...    0    0    0]
 [7641 4581 3018 ...    0    0    0]
 ...
 [6469 7513 9528 ...    0    0    0]
 [9249 3244 1021 ...    0    0    0]
 [6634 5957 5830 ...    0    0    0]]


In [31]:
y = keras.utils.to_categorical(y, 3)
y_test = keras.utils.to_categorical(y_test, 3)

In [32]:
modelEmb = Sequential()
modelEmb.add(Embedding(vs, 500, input_length=max_length))
modelEmb.add(Flatten())
modelEmb.add(Dense(64, activation='relu'))
modelEmb.add(Dense(64, activation='relu'))
modelEmb.add(Dense(64, activation='relu'))
modelEmb.add(Dense(3, activation='softmax'))
# compile the model
modelEmb.compile(optimizer='adam',loss = keras.losses.categorical_crossentropy, metrics=['accuracy'])
# summarize the model
print(modelEmb.summary())
# fit the model
modelEmb.fit(p_docs, y, epochs = 20, callbacks = [early_stopping], verbose=1, validation_data = (p_docs_test, y_test))

score = modelEmb.evaluate(p_docs_test, y_test, verbose=1)

print('Test loss:', score[0])
print('Test accuracy:', score[1])

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (None, 34, 500)           5000000   
_________________________________________________________________
flatten_2 (Flatten)          (None, 17000)             0         
_________________________________________________________________
dense_8 (Dense)              (None, 64)                1088064   
_________________________________________________________________
dense_9 (Dense)              (None, 64)                4160      
_________________________________________________________________
dense_10 (Dense)             (None, 64)                4160      
_________________________________________________________________
dense_11 (Dense)             (None, 3)                 195       
Total params: 6,096,579
Trainable params: 6,096,579
Non-trainable params: 0
____________________________________________

In [33]:
emotion_final_extracted = emotion_final[['text', 'label']]
text_emotion_extracted = text_emotion[['text', 'label']]
new_emotion_text = pd.concat([emotion_final_extracted, text_emotion_extracted])

In [34]:
new_emotion_text["label"].replace({'happiness': 'happy'}, inplace=True)

In [37]:
conditions = [(new_emotion_text['label'] == "sadness") | (new_emotion_text['label'] == "worry") | (new_emotion_text['label'] == "hate") | (new_emotion_text['label'] == "anger") | new_emotion_text['label'] == "fear" , (new_emotion_text['label'] == "boredom") | (new_emotion_text['label'] == "neutral") | (new_emotion_text['label'] == "surprise"), (new_emotion_text['label'] == "enthusiasm")   | (new_emotion_text['label'] == "love") | (new_emotion_text['label'] == "fun") | (new_emotion_text['label'] == "happy") | (new_emotion_text['label'] == "relief")] 

In [38]:
new_emotion_text['binary_emotion'] = np.select(conditions, values)

In [39]:
new_emotion_text.head(15)

text     label  \
0                             i didnt feel humiliated   sadness   
1   i can go from feeling so hopeless to so damned...   sadness   
2    im grabbing a minute to post i feel greedy wrong     anger   
3   i am ever feeling nostalgic about the fireplac...      love   
4                                i am feeling grouchy     anger   
5   ive been feeling a little burdened lately wasn...   sadness   
6   ive been taking or milligrams or times recomme...  surprise   
7   i feel as confused about life as a teenager or...      fear   
8   i have been with petronas for years i feel tha...     happy   
9                                 i feel romantic too      love   
10  i feel like i have to make the suffering i m s...   sadness   
11  i do feel that running is a divine experience ...     happy   
12  i think it s the easiest time of year to feel ...     anger   
13                 i feel low energy i m just thirsty   sadness   
14  i have immense sympathy with the general point...     happy   

    binary_emotion  
0                0  
1                0  
2                0  
3                2  
4                0  
5                0  
6                1  
7                0  
8                2  
9                2  
10               0  
11               2  
12               0  
13               0  
14               2

In [54]:
X = new_emotion_text['text']
y = new_emotion_text['binary_emotion']
X_test = new_emotion_text['text']
y_test = new_emotion_text['binary_emotion']

In [55]:
X = X.to_list()
y = y.to_numpy()
X_test = X_test.to_list()
y_test = y_test.to_numpy()

In [56]:
vs = 10000
enc_docs = [one_hot(d , vs) for d in X]
enc_docs_test = [one_hot(d , vs) for d in X_test]

In [57]:
max_length = 66
p_docs = pad_sequences(enc_docs, maxlen = max_length, padding = 'post')
p_docs_test = pad_sequences(enc_docs_test, maxlen = max_length, padding = 'post')
print(p_docs)

[[4356 7128 9285 ...    0    0    0]
 [4356 1407 9160 ...    0    0    0]
 [ 797  684 6370 ...    0    0    0]
 ...
 [6469 7513 9528 ...    0    0    0]
 [9249 3244 1021 ...    0    0    0]
 [6634 5957 5830 ...    0    0    0]]


In [58]:
print(p_docs_test)

[[4356 7128 9285 ...    0    0    0]
 [4356 1407 9160 ...    0    0    0]
 [ 797  684 6370 ...    0    0    0]
 ...
 [6469 7513 9528 ...    0    0    0]
 [9249 3244 1021 ...    0    0    0]
 [6634 5957 5830 ...    0    0    0]]


In [59]:
y = keras.utils.to_categorical(y, 3)
y_test = keras.utils.to_categorical(y_test, 3)

In [46]:
modelEmb = Sequential()
modelEmb.add(Embedding(vs, 500, input_length=max_length))
modelEmb.add(Flatten())
modelEmb.add(Dense(64, activation='relu'))
modelEmb.add(Dense(64, activation='relu'))
modelEmb.add(Dense(64, activation='relu'))
modelEmb.add(Dense(3, activation='softmax'))
# compile the model
modelEmb.compile(optimizer='adam',loss = keras.losses.categorical_crossentropy, metrics=['accuracy'])
# summarize the model
print(modelEmb.summary())
# fit the model
modelEmb.fit(p_docs, y, epochs = 20, callbacks = [early_stopping], verbose=1, validation_data = (p_docs_test, y_test))

score = modelEmb.evaluate(p_docs_test, y_test, verbose=1)

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_3 (Embedding)      (None, 66, 500)           5000000   
_________________________________________________________________
flatten_3 (Flatten)          (None, 33000)             0         
_________________________________________________________________
dense_12 (Dense)             (None, 64)                2112064   
_________________________________________________________________
dense_13 (Dense)             (None, 64)                4160      
_________________________________________________________________
dense_14 (Dense)             (None, 64)                4160      
_________________________________________________________________
dense_15 (Dense)             (None, 3)                 195       
Total params: 7,120,579
Trainable params: 7,120,579
Non-trainable params: 0
____________________________________________

In [47]:
X = text_emotion['text']
y = text_emotion['binary_emotion']
X_test = emotion_final['text']
y_test = emotion_final['binary_emotion']

In [48]:
X = X.to_list()
y = y.to_numpy()
X_test = X_test.to_list()
y_test = y_test.to_numpy()

In [49]:
vs = 10000
enc_docs = [one_hot(d , vs) for d in X]
enc_docs_test = [one_hot(d , vs) for d in X_test]

In [50]:
max_length = 66
p_docs = pad_sequences(enc_docs, maxlen = max_length, padding = 'post')
p_docs_test = pad_sequences(enc_docs_test, maxlen = max_length, padding = 'post')
print(p_docs)

[[ 789 4356 7578 ...    0    0    0]
 [1967 1450 4705 ...    0    0    0]
 [7641 4581 3018 ...    0    0    0]
 ...
 [6469 7513 9528 ...    0    0    0]
 [9249 3244 1021 ...    0    0    0]
 [6634 5957 5830 ...    0    0    0]]


In [52]:
print(p_docs_test)

[[4356 7128 9285 ...    0    0    0]
 [4356 1407 9160 ...    0    0    0]
 [ 797  684 6370 ...    0    0    0]
 ...
 [8657 5975 8254 ...    0    0    0]
 [4052 5258 8978 ...    0    0    0]
 [4356  609 6353 ...    0    0    0]]


In [53]:
modelEmb = Sequential()
modelEmb.add(Embedding(vs, 500, input_length=max_length))
modelEmb.add(Flatten())
modelEmb.add(Dense(64, activation='relu'))
modelEmb.add(Dense(64, activation='relu'))
modelEmb.add(Dense(64, activation='relu'))
modelEmb.add(Dense(3, activation='softmax'))
# compile the model
modelEmb.compile(optimizer='adam',loss = keras.losses.categorical_crossentropy, metrics=['accuracy'])
# summarize the model
print(modelEmb.summary())
# fit the model
modelEmb.fit(p_docs, y, epochs = 20, callbacks = [early_stopping], verbose=1, validation_data = (p_docs_test, y_test))

score = modelEmb.evaluate(p_docs_test, y_test, verbose=1)

print('Test loss:', score[0])
print('Test accuracy:', score[1])

Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_5 (Embedding)      (None, 66, 500)           5000000   
_________________________________________________________________
flatten_5 (Flatten)          (None, 33000)             0         
_________________________________________________________________
dense_20 (Dense)             (None, 64)                2112064   
_________________________________________________________________
dense_21 (Dense)             (None, 64)                4160      
_________________________________________________________________
dense_22 (Dense)             (None, 64)                4160      
_________________________________________________________________
dense_23 (Dense)             (None, 3)                 195       
Total params: 7,120,579
Trainable params: 7,120,579
Non-trainable params: 0
____________________________________________

ValueError: in user code:

    /home/apprenant/simplon_project/Brief-Emotion-Analysis-Text/env/lib/python3.8/site-packages/keras/engine/training.py:830 train_function  *
        return step_function(self, iterator)
    /home/apprenant/simplon_project/Brief-Emotion-Analysis-Text/env/lib/python3.8/site-packages/keras/engine/training.py:813 run_step  *
        outputs = model.train_step(data)
    /home/apprenant/simplon_project/Brief-Emotion-Analysis-Text/env/lib/python3.8/site-packages/keras/engine/training.py:771 train_step  *
        loss = self.compiled_loss(
    /home/apprenant/simplon_project/Brief-Emotion-Analysis-Text/env/lib/python3.8/site-packages/keras/engine/compile_utils.py:201 __call__  *
        loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    /home/apprenant/simplon_project/Brief-Emotion-Analysis-Text/env/lib/python3.8/site-packages/keras/losses.py:142 __call__  *
        losses = call_fn(y_true, y_pred)
    /home/apprenant/simplon_project/Brief-Emotion-Analysis-Text/env/lib/python3.8/site-packages/keras/losses.py:246 call  *
        return ag_fn(y_true, y_pred, **self._fn_kwargs)
    /home/apprenant/simplon_project/Brief-Emotion-Analysis-Text/env/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py:206 wrapper  **
        return target(*args, **kwargs)
    /home/apprenant/simplon_project/Brief-Emotion-Analysis-Text/env/lib/python3.8/site-packages/tensorflow/python/keras/losses.py:1643 categorical_crossentropy
        return backend.categorical_crossentropy(
    /home/apprenant/simplon_project/Brief-Emotion-Analysis-Text/env/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py:206 wrapper
        return target(*args, **kwargs)
    /home/apprenant/simplon_project/Brief-Emotion-Analysis-Text/env/lib/python3.8/site-packages/tensorflow/python/keras/backend.py:4862 categorical_crossentropy
        target.shape.assert_is_compatible_with(output.shape)
    /home/apprenant/simplon_project/Brief-Emotion-Analysis-Text/env/lib/python3.8/site-packages/tensorflow/python/framework/tensor_shape.py:1161 assert_is_compatible_with
        raise ValueError("Shapes %s and %s are incompatible" % (self, other))

    ValueError: Shapes (32, 1) and (32, 3) are incompatible
